# .gitpod.yml
image: gitpod/workspace-full

tasks:
  - name: Setup Environment
    init: |
      echo "Installing project dependencies..."
      sudo apt-get update
      sudo apt-get install -y curl vim
    command: |
      echo "Environment ready ✅"